baseURL = "https://npm.install.express"
languageCode = "ko-KR"
title = "npm.install.express"

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"