baseURL = "https://npm.install.express"
languageCode = "ko-KR"
title = "npm.install.express"
publishDir = "./wirekang.github.io/"

[markup.goldmark.renderer]
unsafe= true

[markup.tableOfContents]
  endLevel   = 6
  ordered    = false
  startLevel = 1

[markup.highlight]
  lineNos = true
  noClasses = true
  tabWidth = 2
  style = "github"


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"